name: watercrop_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  firebase_auth: ^4.2.1
  page_transition: "^2.0.9"
  provider: ^6.0.5
  cloud_firestore: ^4.12.2
  intl: ^0.18.1
  file_picker: ^6.1.1
  csv: ^5.1.1
  jiffy: ^6.2.1
  plant_icons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/

