class Safra {
  String uid;
  int ano;
  String cultura;
  String cultivar;
  int sow_day;
  int days_since_sow;
  int vget4_day;
  int flower_day;
  int grain_fill_day;
  int matur_day;
  double field_cap_1;
  double field_cap_2;
  double field_cap_3;
  double perm_with_point_1;
  double perm_with_point_2;
  double perm_with_point_3;
  int sow_root_prof;
  int veget4_root_prof;
  int flower_root_prof;
  int grain_fill_root_prof;
  int matur_root_prof;
  double sow_cult_coeff;
  double veget4_cult_coeff;
  double flower_cult_coeff;
  double grain_fill_cult_coeff;
  double matur_cult_coeff;
  int pivot_cap;
  double sow_pivot_optimal_limit;
  double veget4_pivot_optimal_limit;
  double flower_pivot_optimal_limit;
  double grain_pivot_optimal_limit;
  double matur_pivot_optimal_limit;
  double sow_critical_limit;
  double veget4_critical_limit;
  double flower_critical_limit;
  double grain_critical_limit;
  double matur_critical_limit;
  List? dados_meteorologicos;
  List? irrigation;

  Safra(
      {required this.uid,
      required this.ano,
      required this.cultura,
      required this.cultivar,
      required this.sow_day,
      required this.days_since_sow,
      required this.vget4_day,
      required this.flower_day,
      required this.grain_fill_day,
      required this.matur_day,
      required this.field_cap_1,
      required this.field_cap_2,
      required this.field_cap_3,
      required this.perm_with_point_1,
      required this.perm_with_point_2,
      required this.perm_with_point_3,
      required this.sow_root_prof,
      required this.veget4_root_prof,
      required this.flower_root_prof,
      required this.grain_fill_root_prof,
      required this.matur_root_prof,
      required this.sow_cult_coeff,
      required this.veget4_cult_coeff,
      required this.flower_cult_coeff,
      required this.grain_fill_cult_coeff,
      required this.matur_cult_coeff,
      required this.pivot_cap,
      required this.sow_pivot_optimal_limit,
      required this.veget4_pivot_optimal_limit,
      required this.flower_pivot_optimal_limit,
      required this.grain_pivot_optimal_limit,
      required this.matur_pivot_optimal_limit,
      required this.sow_critical_limit,
      required this.veget4_critical_limit,
      required this.flower_critical_limit,
      required this.grain_critical_limit,
      required this.matur_critical_limit,
      this.dados_meteorologicos,
      this.irrigation});
}
