// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-CFtjFLXJCOlAzPbfAHUEoiZVoyNjvE',
    appId: '1:76253606813:web:7b95b8737953a04018b574',
    messagingSenderId: '76253606813',
    projectId: 'watercrop-568fe',
    authDomain: 'watercrop-568fe.firebaseapp.com',
    storageBucket: 'watercrop-568fe.appspot.com',
    measurementId: 'G-SQJTH09Y09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBRd1a8hj1_V4FqI1KSMFYbbBJdUB61fk',
    appId: '1:76253606813:android:ea73ada19a5401b118b574',
    messagingSenderId: '76253606813',
    projectId: 'watercrop-568fe',
    storageBucket: 'watercrop-568fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUzFoR2FE0ZZrv_6-LbAl37MWB-Nx6kR4',
    appId: '1:76253606813:ios:072737f6250bc89918b574',
    messagingSenderId: '76253606813',
    projectId: 'watercrop-568fe',
    storageBucket: 'watercrop-568fe.appspot.com',
    iosClientId: '76253606813-onm8r58419bk9jj64pdclhh3ooiamlc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.watercropApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUzFoR2FE0ZZrv_6-LbAl37MWB-Nx6kR4',
    appId: '1:76253606813:ios:7d41100d217e301718b574',
    messagingSenderId: '76253606813',
    projectId: 'watercrop-568fe',
    storageBucket: 'watercrop-568fe.appspot.com',
    iosClientId: '76253606813-hcklr63vi91o50t9p88lo2rtmvl0qpcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.watercropApp.RunnerTests',
  );
}
